(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-05-24 14:24:12
  From session:  untitled session
  Captured on:  2017-05-24 14:23:12
  From server:  SUT
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "mainmenu"
Click "iciyt"
Click "playervplayer"
Click "playervplayer_0001"
Click "playervai"
Click "stalemate"
Click "opengameloadgamedeletegame"
